### PR TITLE
Support to config log rotate in kubeedge

### PR DESCRIPTION
**Pull request by clarklee92**
Hello,
Log rotate is required by users, I try to give this PR to make rotate configurable. You may put the content in `logging.yaml` like this:
```
rollingPolicy: "daily" # size or daily
logRotateSize: 10 #M Bytes, if rolling policy is 'size'
logBackupCount: 7
logRotateDate: 1 # day step
```
Signed-off-by: clarklee <clarklee1992@hotmail.com>

### CODE REVIEW

**Comment by sids-b** [comment]
@clarklee92 , we are changing the logging library to klog... Please take a look https://github.com/kubeedge/kubeedge/pull/1019

cc @kevin-wangzefeng @fisherxu @kadisi

**Comment by fisherxu** [comment]
> @clarklee92 , we are changing the logging library to klog... Please take a look 

Thanks for your contribution, and yes, we are now changing the logging library to klog, could  please take a review :) @clarklee92

**Comment by clarklee92** [comment]
> > @clarklee92 , we are changing the logging library to klog... Please take a look
> 
> Thanks for your contribution, and yes, we are now changing the logging library to klog, could please take a review :) @clarklee92

That's all right.

**Comment by subpathdev** [comment]
Later today I will add an unit file to run the edgecore.
Would this resolve your issue @clarklee92?

**Comment by fisherxu** [comment]
`beehive` has been moved to `kubeedge/staging`, we can raise PR under `kubeedge/kubeedge`, close this now :)
/close

**Pull request closed without merging**
