### PR TITLE
Travis CI Configuration for Beehive Repo

### LINKED ISSUE #4: CI/CD setup for beehive repository.
We need to have CI/CD setup to check if any new modifications breaks existing functionality. Also to run static checks.

### PR DESCRIPTION
**Pull request by pavan187**
Adding Travis-CI support for Beehive Repository

Fixes#4

### CODE REVIEW

**Comment by pavan187** [comment]
cc @m1093782566

**Comment by rohitsardesai83** [comment]
@pavan187 , can this be merged ? or any further changes required ?

**Comment by subpathdev** [comment]
@rohitsardesai83 we need the makefile to merge this pr

**Pull request merged**
