### PR TITLE
add owners file for beehive

### PR DESCRIPTION
**Pull request by kevin-wangzefeng**
We don't have owners file in this repo yet, which blocks the bot automation.
This PR is to fix it.

### CODE REVIEW

**Comment by edisonxiang** [comment]
Thanks @kevin-wangzefeng

**Comment by sids-b** [comment]
Thanks @kevin-wangzefeng 

+1 binding

**Comment by sids-b** [comment]
/hold

Lets wait till friday for merge

**Review by sids-b — APPROVED** [review]
Thanks @kevin-wangzefeng

**Pull request merged**
